// Generated by gencpp from file turtles/Turtle.msg
// DO NOT EDIT!


#ifndef TURTLES_MESSAGE_TURTLE_H
#define TURTLES_MESSAGE_TURTLE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace turtles
{
template <class ContainerAllocator>
struct Turtle_
{
  typedef Turtle_<ContainerAllocator> Type;

  Turtle_()
    : id(0)
    , name()
    , quality(0)  {
    }
  Turtle_(const ContainerAllocator& _alloc)
    : id(0)
    , name(_alloc)
    , quality(0)  {
  (void)_alloc;
    }



   typedef int16_t _id_type;
  _id_type id;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _name_type;
  _name_type name;

   typedef int8_t _quality_type;
  _quality_type quality;





  typedef boost::shared_ptr< ::turtles::Turtle_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::turtles::Turtle_<ContainerAllocator> const> ConstPtr;

}; // struct Turtle_

typedef ::turtles::Turtle_<std::allocator<void> > Turtle;

typedef boost::shared_ptr< ::turtles::Turtle > TurtlePtr;
typedef boost::shared_ptr< ::turtles::Turtle const> TurtleConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::turtles::Turtle_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::turtles::Turtle_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace turtles

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg'], 'turtles': ['/home/daniel/repos/infinite-turtles/src/turtles/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::turtles::Turtle_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::turtles::Turtle_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::turtles::Turtle_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::turtles::Turtle_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::turtles::Turtle_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::turtles::Turtle_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::turtles::Turtle_<ContainerAllocator> >
{
  static const char* value()
  {
    return "52e5c16d048760fa40373372233ace76";
  }

  static const char* value(const ::turtles::Turtle_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x52e5c16d048760faULL;
  static const uint64_t static_value2 = 0x40373372233ace76ULL;
};

template<class ContainerAllocator>
struct DataType< ::turtles::Turtle_<ContainerAllocator> >
{
  static const char* value()
  {
    return "turtles/Turtle";
  }

  static const char* value(const ::turtles::Turtle_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::turtles::Turtle_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int16 id\n"
"string name\n"
"int8 quality\n"
;
  }

  static const char* value(const ::turtles::Turtle_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::turtles::Turtle_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.id);
      stream.next(m.name);
      stream.next(m.quality);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Turtle_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::turtles::Turtle_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::turtles::Turtle_<ContainerAllocator>& v)
  {
    s << indent << "id: ";
    Printer<int16_t>::stream(s, indent + "  ", v.id);
    s << indent << "name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.name);
    s << indent << "quality: ";
    Printer<int8_t>::stream(s, indent + "  ", v.quality);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TURTLES_MESSAGE_TURTLE_H
